### ISSUE TITLE
psycopg2.IntegrityError: duplicate key value violates unique constraint "auth_permission_pkey" na upgrade van v3 -> v4

### ISSUE THREAD

**Issue by megapearl** [dsmrreader/dsmr-reader#1073]
- DSMR-reader versie:  4.1.1
- Type RaspberryPi or server:   Debian 10 x64 virtualised
- Standaardinstallatie of Docker:   Standaard in virtualenv
- DSMR-protocol slimme meter:  v5
- Datalogger draait extern op een Pi3
---

Na het volgen van: https://dsmr-reader.readthedocs.io/en/v4/faq/v4_upgrade.html

Waarschijnlijk iets in de database niet lekker, ik heb dit soort meldingen weleens vaker gehad.
Hoe is de duplicate ook alweer te verwijderen uit de postgresql db? of kan ik deze fout negeren?

```
psycopg2.IntegrityError: duplicate key value violates unique constraint "auth_permission_pkey"
DETAIL:  Key (id)=(20) already exists.

```
```
root@mediaserver:/home/dsmr/dsmr-reader# sudo su - dsmr
(dsmrreader) dsmr@mediaserver:~/dsmr-reader$ ./deploy.sh


 --- You are currently running version:
4.1.1


 --- Checking Python version.
Running Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]


 --- Pulling remote repository for new commits...


 --- Merging/updating checkout.
Already up to date.


 >>> Running post-deployment script. <<<


 --- Checking whether VirtualEnv is activated.


 --- Checking Python version.
Running Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]


 --- Checking & synchronizing base requirements for changes.
Requirement already up-to-date: coreapi==2.3.3 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 1)) (2.3.3)
Requirement already up-to-date: crcmod==1.7 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 2)) (1.7)
Requirement already up-to-date: django==3.0.8 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 3)) (3.0.8)
Requirement already up-to-date: django-admin-rangefilter==0.6.1 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 4)) (0.6.1)
Requirement already up-to-date: django-colorfield==0.3.2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 5)) (0.3.2)
Requirement already up-to-date: django-debug-toolbar==2.2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 6)) (2.2)
Requirement already up-to-date: django-filter==2.3.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 7)) (2.3.0)
Requirement already up-to-date: djangorestframework==3.11 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 8)) (3.11.0)
Requirement already up-to-date: django-solo==1.1.3 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 9)) (1.1.3)
Requirement already up-to-date: dropbox==10.3.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 10)) (10.3.0)
Requirement already up-to-date: gunicorn==20.0.4 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 11)) (20.0.4)
Requirement already up-to-date: influxdb==5.3.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 12)) (5.3.0)
Requirement already up-to-date: paho-mqtt==1.5.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 13)) (1.5.0)
Requirement already up-to-date: pyserial==3.4 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 14)) (3.4)
Requirement already up-to-date: pyserial-asyncio==0.4 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 15)) (0.4)
Requirement already up-to-date: python-dateutil==2.8.1 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 16)) (2.8.1)
Requirement already up-to-date: python-decouple==3.3 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 17)) (3.3)
Requirement already up-to-date: pytz==2020.1 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 18)) (2020.1)
Requirement already up-to-date: requests==2.24.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 19)) (2.24.0)
Requirement already up-to-date: urllib3==1.25.10 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from -r dsmrreader/provisioning/requirements/base.txt (line 20)) (1.25.10)
Requirement already satisfied, skipping upgrade: coreschema in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from coreapi==2.3.3->-r dsmrreader/provisioning/requirements/base.txt (line 1)) (0.0.4)
Requirement already satisfied, skipping upgrade: itypes in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from coreapi==2.3.3->-r dsmrreader/provisioning/requirements/base.txt (line 1)) (1.2.0)
Requirement already satisfied, skipping upgrade: uritemplate in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from coreapi==2.3.3->-r dsmrreader/provisioning/requirements/base.txt (line 1)) (3.0.1)
Requirement already satisfied, skipping upgrade: asgiref~=3.2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from django==3.0.8->-r dsmrreader/provisioning/requirements/base.txt (line 3)) (3.2.10)
Requirement already satisfied, skipping upgrade: sqlparse>=0.2.2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from django==3.0.8->-r dsmrreader/provisioning/requirements/base.txt (line 3)) (0.3.1)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from dropbox==10.3.0->-r dsmrreader/provisioning/requirements/base.txt (line 10)) (1.15.0)
Requirement already satisfied, skipping upgrade: setuptools>=3.0 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from gunicorn==20.0.4->-r dsmrreader/provisioning/requirements/base.txt (line 11)) (49.2.1)
Requirement already satisfied, skipping upgrade: msgpack==0.6.1 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from influxdb==5.3.0->-r dsmrreader/provisioning/requirements/base.txt (line 12)) (0.6.1)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from requests==2.24.0->-r dsmrreader/provisioning/requirements/base.txt (line 19)) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from requests==2.24.0->-r dsmrreader/provisioning/requirements/base.txt (line 19)) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from requests==2.24.0->-r dsmrreader/provisioning/requirements/base.txt (line 19)) (2.10)
Requirement already satisfied, skipping upgrade: jinja2 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from coreschema->coreapi==2.3.3->-r dsmrreader/provisioning/requirements/base.txt (line 1)) (2.11.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages (from jinja2->coreschema->coreapi==2.3.3->-r dsmrreader/provisioning/requirements/base.txt (line 1)) (1.1.1)


 --- Checking & synchronizing database changes/migrations.
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dsmr_api, dsmr_backend, dsmr_backup, dsmr_consumption, dsmr_datalogger, dsmr_frontend, dsmr_influxdb, dsmr_mindergas, dsmr_mqtt, dsmr_notification, dsmr_pvoutput, dsmr_stats, dsmr_weather, sessions
Running migrations:
  Applying dsmr_backend.0015_backend_restart_required... OK
  Applying dsmr_datalogger.0023_network_socket_datalogger... OK
  Applying dsmr_datalogger.0024_enable_retention_by_default... OK
  Applying dsmr_datalogger.0025_datalogger_mandatory_sleep_update... OK
  Applying dsmr_datalogger.0026_datalogger_restart_required... OK
  Applying dsmr_frontend.0038_always_require_login... OK
  Applying dsmr_frontend.0039_retention_headsup... OK
  Applying dsmr_frontend.0040_v4_1_0_release... OK
  Applying dsmr_influxdb.0001_influxdb_integration... OK
  Applying dsmr_influxdb.0002_influxdb_optional_credentials... OK
  Applying dsmr_influxdb.0003_influxdb_outgoing_measurements... OK
  Applying dsmr_influxdb.0004_client_settings_update... OK
  Applying dsmr_mqtt.0015_continuous_client... OK
  Applying dsmr_mqtt.0016_client_settings_update... OK
Traceback (most recent call last):
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "auth_permission_pkey"
DETAIL:  Key (id)=(20) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 256, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/core/management/sql.py", line 50, in emit_post_migrate_signal
    **kwargs
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/contrib/auth/management/__init__.py", line 83, in create_permissions
    Permission.objects.using(using).bulk_create(perms)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 493, in bulk_create
    objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts,
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 1223, in _batched_insert
    ignore_conflicts=ignore_conflicts,
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_permission_pkey"
DETAIL:  Key (id)=(20) already exists.



 --- Checking & synchronizing static file changes.

170 static files copied to '/var/www/dsmrreader/static', 387 unmodified.


 --- Reloading running apps...

 * Reloading process: dsmr_webinterface (Gunicorn)   [OK]
 * Reloading process: dsmr_backend                   [OK]
 * Reloading process: dsmr_datalogger                [!!] PID file does not exist or the datalogger is disabled (Should it run? As sudo user, try 'sudo supervisorctl start dsmr_datalogger')


 --- Clearing cache...


 --- Deployed version:
4.1.1


 >>> Deployment complete. <<<
(dsmrreader) dsmr@mediaserver:~/dsmr-reader$

```

Groetjes,
Donald.

**Comment by dennissiemensma** [comment]
Probeer: https://dsmr-reader.readthedocs.io/en/v4/faq.html#how-do-i-fix-errors-such-as-detail-key-id-123-already-exists . En als dat het niet oplost, wat geeft de output van de commands uit de volgende comment? https://github.com/dennissiemensma/dsmr-reader/issues/201#issuecomment-269916675

**Comment by megapearl** [comment]
Hoi Dennis,

```
# Note: dsmr_sqlsequencereset is only available in DSMR-reader v3.3.0 and higher
sudo su - dsmr
./manage.py dsmr_sqlsequencereset
```
Heeft het inderdaad opgelost, dank je wel!

```
root@mediaserver:/home/donald# sudo su - dsmr
(dsmrreader) dsmr@mediaserver:~/dsmr-reader$ ./manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
dsmr_api
 [X] 0001_api_settings
 [X] 0002_generate_random_auth_key
 [X] 0003_create_api_user
dsmr_backend
 [X] 0001_backend_language
 [X] 0002_email_settings
 [X] 0003_scheduled_processes
 [X] 0004_backend_schedule_process_active_flag
 [X] 0005_schedule_auto_update_check
 [X] 0006_backend_auto_update_check
 [X] 0007_schedule_stats_generator
 [X] 0008_scheduled_process_fields
 [X] 0009_update_email_settings_mail_from
 [X] 0010_process_sleep
 [X] 0011_disable_capabilities
 [X] 0012_fix_email_from
 [X] 0013_allow_higher_backend_sleep
 [X] 0014_verbose_field_translations
 [X] 0015_backend_restart_required
dsmr_backup
 [X] 0001_initial
 [X] 0002_settings_documentation
 [X] 0003_dropbox_sync_field
 [X] 0004_custom_backup_path
 [X] 0005_email_backup_settings
 [X] 0006_scheduled_email_backup
 [X] 0007_remove_backupsettings_compress
 [X] 0008_verbose_field_translations
 [X] 0009_compression_level
 [X] 0010_schedule_backup
 [X] 0011_remove_backupsettings_latest_backup
dsmr_consumption
 [X] 0001_squashed_0004_recalculate_gas_consumption
 [X] 0002_verbose_text
 [X] 0003_electricity_consumption_indexes
 [X] 0004_merge_electricity_tariffs
 [X] 0005_phase_currently_delivered
 [X] 0006_dsmr_firmware_v5
 [X] 0007_settings_documentation
 [X] 0008_energysupplier_return_prices
 [X] 0009_consumption_settings_text
 [X] 0010_phases_currently_returned
 [X] 0011_track_phase_voltages
 [X] 0012_add_voltage_indexes
 [X] 0013_schedule_generate_consumption
 [X] 0014_gas_grouping
 [X] 0015_track_power_current
dsmr_datalogger
 [X] 0001_squashed_0005_optional_gas_readings
 [X] 0002_meta_names
 [X] 0003_telegram_checksum
 [X] 0004_phase_currently_delivered
 [X] 0005_verify_telegram_crc_setting
 [X] 0006_dsmr_firmware_v5
 [X] 0007_dsmrreading_timestamp_index
 [X] 0008_dsmrreading_help_text
 [X] 0009_retention_settings
 [X] 0010_phases_currently_returned
 [X] 0011_raw_telegram_insight
 [X] 0012_track_phase_voltages
 [X] 0013_remove_datalogger_track_settings
 [X] 0014_remove_optional_crc_check
 [X] 0015_datalogger_foreign_countries
 [X] 0016_process_sleep
 [X] 0017_log_telegrams
 [X] 0018_meterstatistics_no_autonow
 [X] 0019_verbose_field_translations
 [X] 0020_track_power_current
 [X] 0021_schedule_retention_data_rotation
 [X] 0022_three_month_retention
 [X] 0023_network_socket_datalogger
 [X] 0024_enable_retention_by_default
 [X] 0025_datalogger_mandatory_sleep_update
 [X] 0026_datalogger_restart_required
dsmr_frontend
 [X] 0001_initial
 [X] 0002_recent_history_weeks
 [X] 0003_drop_history_page
 [X] 0004_chart_colors
 [X] 0005_notifications
 [X] 0006_notifications_initial
 [X] 0007_merge_electricity_tariffs
 [X] 0008_merge_electricity_tariffs_notification
 [X] 0009_docs_no_reverse_match
 [X] 0010_drop_reverse_dashboard_graphs_setting
 [X] 0011_phase_currently_delivered
 [X] 0012_frontendsettings_dashboard_graph_width
 [X] 0013_echart_graphs_message
 [X] 0014_phases_currently_returned
 [X] 0015_notification_meta
 [X] 0016_v200_release
 [X] 0017_v201_release
 [X] 0018_v202_release
 [X] 0019_v210_release
 [X] 0020_v230_release
 [X] 0021_v260_release
 [X] 0022_v270_release
 [X] 0023_v290_release
 [X] 0024_v2100_release
 [X] 0025_increase_max_dashboard_graph_width
 [X] 0026_v2140_release
 [X] 0027_v215_release
 [X] 0028_v3_0_fix_upgrade_redirect
 [X] 0029_gas_graph_style
 [X] 0030_electricity_graph_style
 [X] 0031_tariff_names
 [X] 0032_v3_4_0_release
 [X] 0033_django_colorfield_update
 [X] 0034_mysql_timezone_support
 [X] 0035_graphs_range
 [X] 0036_graphs_zoom
 [X] 0037_v3_12_0_release
 [X] 0038_always_require_login
 [X] 0039_retention_headsup
 [X] 0040_v4_1_0_release
dsmr_influxdb
 [X] 0001_influxdb_integration
 [X] 0002_influxdb_optional_credentials
 [X] 0003_influxdb_outgoing_measurements
 [X] 0004_client_settings_update
dsmr_mindergas
 [X] 0001_mindergas
 [X] 0002_mindergas_notification
 [X] 0003_mindergas_next_export_datetime
 [X] 0004_mindergas_latest_sync
 [X] 0005_schedule_mindergas_export
dsmr_mqtt
 [X] 0001_mqtt_settings
 [X] 0002_daytotalsmqttsettings
 [X] 0003_splittopicmeterstatisticsmqttsettings
 [X] 0004_phases_currently_returned
 [X] 0005_mqtt_use_local_timezone
 [X] 0006_mqtt_refactoring
 [X] 0007_mqtts
 [X] 0008_mqtt_null_payload
 [X] 0009_remove_optional_debug
 [X] 0010_mqtt_gas_consumption
 [X] 0011_mqtt_meta_description
 [X] 0012_mqtt_voltage_defaults
 [X] 0013_process_sleep
 [X] 0014_mqtt_telegram_defaults
 [X] 0015_continuous_client
 [X] 0016_client_settings_update
dsmr_notification
 [X] 0001_initial
 [X] 0002_notificationsetting_next_notification
 [X] 0003_notification_notification
 [X] 0004_statusnotificationsetting
 [X] 0005_notify_my_android_ended_support
 [X] 0006_support_for_pushover
 [X] 0007_support_for_telegram
dsmr_pvoutput
 [X] 0001_pvoutput_settings
 [X] 0002_pvoutput_latest_sync
dsmr_stats
 [X] 0001_squashed_0016_drop_stats_settings
 [X] 0002_regenerate_missing_gas_data
 [X] 0003_hour_statistics_gas_default
 [X] 0004_hour_statistics_gas_default_retroactive
 [X] 0005_statistics_exportverbose_names
 [X] 0006_min_max_temperature_statistics
 [X] 0007_min_max_temperature_statistics_retroactive
 [X] 0008_meta_names
 [X] 0009_statistics_editable
 [X] 0010_statistics_models_index
 [X] 0011_note_model_index
 [X] 0012_electricity_statistics
 [X] 0013_all_time_low
 [X] 0014_day_total_cost_index
dsmr_weather
 [X] 0001_weather_models
 [X] 0002_meta
 [X] 0003_next_sync_setting
 [X] 0004_next_sync_setting_retroactive
 [X] 0005_weather_refactor_scheduling
 [X] 0006_schedule_weather_update
sessions
 [X] 0001_initial

```
