### ISSUE TITLE
Influxdb start niet (goed)?

### ISSUE THREAD

**Issue by Helloitsme** [dsmrreader/dsmr-reader#1075]
Hallo

Ik heb zojuist v4.1.1. geïnstalleerd (komende vanaf de laatste versie van 3..)  en probeer met Grafana de influxdb data te benaderen. Dat werkt echter niet (Bad Gateway(502) melding)

Als ik op de admin pagina van dsmr kijk dan zie ik geen vinkje staan bij "InfluxDB-integratie wijzigen". als ik zelf dat vinkje zet dan lijkt het alsof er 1x data wordt geschreven (onder Influxdb measurements ) maar daarna stopt het weer?
Als ik dan weer op InfluxDB-integratie wijzigen kijk, dan staat het vinkje weer uit.

**Comment by dennissiemensma** [comment]
Bedankt voor je vraag. Zou je eens in de logfile van dsmr_backend willen kijken? Vermoedelijk is daar de reden te vinden: https://dsmr-reader.readthedocs.io/en/latest/troubleshooting.html#supervisor

De foutafhandeling van deze en andere integraties is vrij behouden, om te voorkomen dat DSMR-reader oneindig iets probeert te doen. Vandaar de wat aggresieve uitschakeling bij fouten. Ik zal nog eens kijken of ik daar iets beters op kan verzinnen.

**Comment by dennissiemensma** [comment]
En als je helemaal uitgebreide logging wilt zien dan kun je eventueel tijdelijk debug logging inschakelen. Dat staat op dezelfde pagina toegelicht.

**Comment by Helloitsme** [comment]
selectie uit de logfile (nadat debug aangezet is)

2020-08-10 18:45:14,246] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 18:45:14,247] ERROR    HTTPSConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73f62450>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 18:47:18,343] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 18:47:18,345] ERROR    HTTPSConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73f40430>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 19:57:58,315] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 19:57:58,316] ERROR    HTTPSConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x73fde3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 19:58:17,644] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 19:58:17,646] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73f896b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:03:10,751] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:03:10,752] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7400c710>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:16:15,794] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:16:15,795] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x740026d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:24:31,216] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:24:31,219] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7403d710>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:31:28,918] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:31:28,920] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7400f750>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
[2020-08-10 20:37:06,464] ERROR    dsmr_backend.management.commands.dsmr_backend: [!] Exception raised. Traceback (most recent call last):
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dsmr/dsmr-reader/dsmr_backend/mixins.py", line 90, in run_once
    self.run(data=self.data, **options)
  File "/home/dsmr/dsmr-reader/dsmr_backend/management/commands/dsmr_backend.py", line 39, in run
    self._check_restart_required()
  File "/home/dsmr/dsmr-reader/dsmr_backend/management/commands/dsmr_backend.py", line 46, in _check_restart_required
    if not BackendSettings.get_solo().restart_required:
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/solo/models.py", line 54, in get_solo
    obj, created = cls.objects.get_or_create(pk=cls.singleton_instance_id)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dsmr/.virtualenvs/dsmrreader/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: terminating connection due to administrator command
SSL connection has been closed unexpectedly


Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:39:19,000] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:39:19,001] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73ff0770>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:47:41,682] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 20:47:41,683] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73f706f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 20:50:11,472] ERROR    MQTT: Failed to connect to broker (localhost:1883), disabling MQTT: [Errno 111] Connection refused
[2020-08-10 20:50:11,548] ERROR    Failed to connect to broker
NoneType: None
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/v4/troubleshooting.html#logging
[2020-08-10 22:02:40,021] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 22:02:40,022] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73f7b730>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
[2020-08-10 22:07:15,785] DEBUG    MQTT: Integration disabled in settings (or due to an error previously)
[2020-08-10 22:07:15,809] DEBUG    INFLUXDB: Integration disabled in settings (or due to an error previously)
[2020-08-10 22:07:15,812] DEBUG    Persistent clients initialized: []
[2020-08-10 22:07:15,816] DEBUG    dsmr_backend.management.commands.dsmr_backend: Starting infinite command loop...
[2020-08-10 22:07:15,841] DEBUG    SP: 1 backend service(s) ready to run
[2020-08-10 22:07:15,847] DEBUG    SP: Running "Generate consumption data" (dsmr_consumption.services.run)
[2020-08-10 22:07:15,918] DEBUG    Compact: Waiting for newer readings before grouping data...
[2020-08-10 22:07:16,179] DEBUG    SP: Rescheduled "Generate consumption data" to 2020-08-10 22:07:30.919820+02:00 (ETA 0:00:14.740807)
[2020-08-10 22:07:18,216] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:19,231] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:19,316] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:20,331] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:20,414] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:21,429] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:21,509] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:22,525] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:22,621] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:23,637] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:23,727] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:24,744] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:24,831] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:25,849] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:25,938] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:26,955] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:27,037] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:28,051] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:28,114] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:29,128] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:29,198] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:30,214] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:30,298] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:31,316] DEBUG    SP: 1 backend service(s) ready to run
[2020-08-10 22:07:31,319] DEBUG    SP: Running "Generate consumption data" (dsmr_consumption.services.run)
[2020-08-10 22:07:31,482] DEBUG    Compact: Processed reading: 11614249 @ 2020-08-10 22:06:08+02:00
[2020-08-10 22:07:31,527] DEBUG    Compact: Processed reading: 11614250 @ 2020-08-10 22:06:18+02:00
[2020-08-10 22:07:31,571] DEBUG    Compact: Processed reading: 11614251 @ 2020-08-10 22:06:28+02:00
[2020-08-10 22:07:31,616] DEBUG    Compact: Processed reading: 11614252 @ 2020-08-10 22:06:38+02:00
[2020-08-10 22:07:31,661] DEBUG    Compact: Processed reading: 11614253 @ 2020-08-10 22:06:48+02:00
[2020-08-10 22:07:31,705] DEBUG    Compact: Processed reading: 11614254 @ 2020-08-10 22:06:58+02:00
[2020-08-10 22:07:31,727] DEBUG    Compact: Waiting for newer readings before grouping data...
[2020-08-10 22:07:31,744] DEBUG    SP: Rescheduled "Generate consumption data" to 2020-08-10 22:07:46.730680+02:00 (ETA 0:00:14.986667)
[2020-08-10 22:07:31,829] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:32,846] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:32,933] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:33,948] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:34,017] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:35,034] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:35,118] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:36,135] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:36,218] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:37,235] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:37,322] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:38,340] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:38,430] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:39,448] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:39,532] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:40,550] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:40,638] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:41,656] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:41,748] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:42,766] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:42,850] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:43,868] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:43,959] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:44,977] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:45,068] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:46,086] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:07:46,179] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:47,198] DEBUG    SP: 1 backend service(s) ready to run
[2020-08-10 22:07:47,201] DEBUG    SP: Running "Generate consumption data" (dsmr_consumption.services.run)
[2020-08-10 22:07:47,255] DEBUG    Compact: Waiting for newer readings before grouping data...
[2020-08-10 22:07:47,276] DEBUG    SP: Rescheduled "Generate consumption data" to 2020-08-10 22:08:02.257980+02:00 (ETA 0:00:14.981379)
[2020-08-10 22:07:47,488] WARNING  Detected backend restart required, stopping process...
[2020-08-10 22:07:47,492] INFO     dsmr_backend.management.commands.dsmr_backend: [i] Detected StopInfiniteRun exception
[2020-08-10 22:07:47,495] INFO     dsmr_backend.management.commands.dsmr_backend: Exiting on next run...
[2020-08-10 22:07:47,496] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:07:48,498] DEBUG    CLIENTS: Terminating 0 client(s)
[2020-08-10 22:07:48,501] DEBUG    dsmr_backend.management.commands.dsmr_backend: Exited
[2020-08-10 22:08:02,089] DEBUG    MQTT: Integration disabled in settings (or due to an error previously)
[2020-08-10 22:08:02,111] DEBUG    INFLUXDB: Initializing InfluxDB client for "localhost:8086"
[2020-08-10 22:08:02,116] DEBUG    INFLUXDB: Creating InfluxDB database "dsmrreader_measurements"
[2020-08-10 22:08:02,290] ERROR    Failed to instantiate InfluxDB connection, disabling InfluxDB integration
[2020-08-10 22:08:02,293] ERROR    HTTPConnectionPool(host='localhost', port=8086): Max retries exceeded with url: /query?q=CREATE+DATABASE+%22dsmrreader_measurements%22&db=dsmrreader_measurements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73f4f730>: Failed to establish a new connection: [Errno 111] Connection refused'))
NoneType: None
[2020-08-10 22:08:02,296] DEBUG    Persistent clients initialized: []
[2020-08-10 22:08:02,299] DEBUG    dsmr_backend.management.commands.dsmr_backend: Starting infinite command loop...
[2020-08-10 22:08:02,320] DEBUG    SP: 1 backend service(s) ready to run
[2020-08-10 22:08:02,324] DEBUG    SP: Running "Generate consumption data" (dsmr_consumption.services.run)
[2020-08-10 22:08:02,393] DEBUG    Compact: Waiting for newer readings before grouping data...
[2020-08-10 22:08:02,652] DEBUG    SP: Rescheduled "Generate consumption data" to 2020-08-10 22:08:17.396050+02:00 (ETA 0:00:14.743271)
[2020-08-10 22:08:04,743] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:08:05,758] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:08:05,841] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:08:06,856] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:08:06,935] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:08:07,952] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:08:08,041] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:08:09,057] DEBUG    SP: 0 backend service(s) ready to run
[2020-08-10 22:08:09,149] DEBUG    dsmr_backend.management.commands.dsmr_backend: Sleeping 1.0s
[2020-08-10 22:08:10,165] DEBUG    SP: 0 backend service(s) ready to run

**Comment by dennissiemensma** [comment]
De host en/of poort klopt niet. Of influxdb draait niet op localhost. Kun je daar wat mee? Debug logging kan trouwens weer uit. Deze fout zou altijd zichtbaar moeten zijn.

**Comment by dennissiemensma** [comment]
Of je hebt Https geselecteerd met verkeerde poort. Of https terwijl influxdb dat niet heeft. Dat kan ook trouwens nog.

**Comment by Helloitsme** [comment]
vraag: moet ik influxdb zelf nog installeren? (heb ik namelijk niet gedaan) of zou dat tijdens de installatie van versie 4 automatisch gebeurd moeten zijn? (daar was ik wellicht ten onrechte vanuit gegaan)

**Comment by Helloitsme** [comment]
daar lijkt het probleem te zitten. "Assumption is the mother of all fuckups..." sorry voor de overlast

**Comment by dennissiemensma** [comment]
Oke dank voor de opheldering. Je zult inderdaad zelf InfluxDb moeten installeren. Doorgaans wil je die namelijk ook niet op je Pi hebben staan, tenzij je een niet-SD-kaart als storage gebruikt. Vandaar.
