### ISSUE TITLE
🙋Elke nacht om 3 uur kapt dsmr er mee, geen idee waarom

### ISSUE THREAD

**Issue by Diondk** [dsmrreader/dsmr-reader#1543]
### Description

Elke nacht om 3 uur kapt dsmr er mee, dan loopt wel de backup van de containers maar tot de vorige update was dit nooit een probleem. nu dus opeens wel, geen idee waarom dit zie ik in mijn container logs staan.

````[2021-12-21 13:21:18 +0100] [84] [INFO] Booting worker with pid: 84
[2021-12-21 13:29:36 +0100] [84] [INFO] Autorestarting worker after current request.
[2021-12-21 13:29:36 +0100] [84] [INFO] Worker exiting (pid: 84)
[2021-12-21 13:29:37 +0100] [85] [INFO] Booting worker with pid: 85
[2021-12-21 13:37:54 +0100] [85] [INFO] Autorestarting worker after current request.
[2021-12-21 13:37:54 +0100] [85] [INFO] Worker exiting (pid: 85)
[2021-12-21 13:37:55 +0100] [86] [INFO] Booting worker with pid: 86
[2021-12-21 13:46:12 +0100] [86] [INFO] Autorestarting worker after current request.
[2021-12-21 13:46:12 +0100] [86] [INFO] Worker exiting (pid: 86)
[2021-12-21 13:46:13 +0100] [87] [INFO] Booting worker with pid: 87
[2021-12-21 13:54:31 +0100] [87] [INFO] Autorestarting worker after current request.
[2021-12-21 13:54:31 +0100] [87] [INFO] Worker exiting (pid: 87)
[2021-12-21 13:54:32 +0100] [88] [INFO] Booting worker with pid: 88
[2021-12-21 14:02:49 +0100] [88] [INFO] Autorestarting worker after current request.
[2021-12-21 14:02:49 +0100] [88] [INFO] Worker exiting (pid: 88)
[2021-12-21 14:02:50 +0100] [89] [INFO] Booting worker with pid: 89
[2021-12-21 14:11:08 +0100] [89] [INFO] Autorestarting worker after current request.
[2021-12-21 14:11:08 +0100] [89] [INFO] Worker exiting (pid: 89)
[2021-12-21 14:11:09 +0100] [90] [INFO] Booting worker with pid: 90
[2021-12-21 14:19:26 +0100] [90] [INFO] Autorestarting worker after current request.
[2021-12-21 14:19:26 +0100] [90] [INFO] Worker exiting (pid: 90)
[2021-12-21 14:19:27 +0100] [91] [INFO] Booting worker with pid: 91
[2021-12-21 14:27:44 +0100] [91] [INFO] Autorestarting worker after current request.
[2021-12-21 14:27:44 +0100] [91] [INFO] Worker exiting (pid: 91)
[2021-12-21 14:27:45 +0100] [92] [INFO] Booting worker with pid: 92
[2021-12-21 14:36:03 +0100] [92] [INFO] Autorestarting worker after current request.
[2021-12-21 14:36:03 +0100] [92] [INFO] Worker exiting (pid: 92)
[2021-12-21 14:36:03 +0100] [93] [INFO] Booting worker with pid: 93
[2021-12-21 14:44:20 +0100] [93] [INFO] Autorestarting worker after current request.
[2021-12-21 14:44:20 +0100] [93] [INFO] Worker exiting (pid: 93)
[2021-12-21 14:44:20 +0100] [94] [INFO] Booting worker with pid: 94
[2021-12-21 14:52:39 +0100] [94] [INFO] Autorestarting worker after current request.
[2021-12-21 14:52:39 +0100] [94] [INFO] Worker exiting (pid: 94)
[2021-12-21 14:52:40 +0100] [95] [INFO] Booting worker with pid: 95
[2021-12-21 15:00:56 +0100] [95] [INFO] Autorestarting worker after current request.
[2021-12-21 15:00:56 +0100] [95] [INFO] Worker exiting (pid: 95)
[2021-12-21 15:00:57 +0100] [96] [INFO] Booting worker with pid: 96
[2021-12-21 15:09:14 +0100] [96] [INFO] Autorestarting worker after current request.
[2021-12-21 15:09:14 +0100] [96] [INFO] Worker exiting (pid: 96)
[2021-12-21 15:09:14 +0100] [97] [INFO] Booting worker with pid: 97
[2021-12-21 15:17:33 +0100] [97] [INFO] Autorestarting worker after current request.
[2021-12-21 15:17:33 +0100] [97] [INFO] Worker exiting (pid: 97)
[2021-12-21 15:17:33 +0100] [98] [INFO] Booting worker with pid: 98
[2021-12-21 15:25:51 +0100] [98] [INFO] Autorestarting worker after current request.
[2021-12-21 15:25:51 +0100] [98] [INFO] Worker exiting (pid: 98)
[2021-12-21 15:25:51 +0100] [99] [INFO] Booting worker with pid: 99
[2021-12-21 15:34:09 +0100] [99] [INFO] Autorestarting worker after current request.
[2021-12-21 15:34:09 +0100] [99] [INFO] Worker exiting (pid: 99)
[2021-12-21 15:34:10 +0100] [100] [INFO] Booting worker with pid: 100
[2021-12-21 15:42:27 +0100] [100] [INFO] Autorestarting worker after current request.
[2021-12-21 15:42:27 +0100] [100] [INFO] Worker exiting (pid: 100)
[2021-12-21 15:42:27 +0100] [101] [INFO] Booting worker with pid: 101
[2021-12-21 15:50:45 +0100] [101] [INFO] Autorestarting worker after current request.
[2021-12-21 15:50:45 +0100] [101] [INFO] Worker exiting (pid: 101)
[2021-12-21 15:50:45 +0100] [102] [INFO] Booting worker with pid: 102
[2021-12-21 15:59:03 +0100] [102] [INFO] Autorestarting worker after current request.
[2021-12-21 15:59:03 +0100] [102] [INFO] Worker exiting (pid: 102)
[2021-12-21 15:59:03 +0100] [103] [INFO] Booting worker with pid: 103
[2021-12-21 16:07:21 +0100] [103] [INFO] Autorestarting worker after current request.
[2021-12-21 16:07:21 +0100] [103] [INFO] Worker exiting (pid: 103)
[2021-12-21 16:07:21 +0100] [104] [INFO] Booting worker with pid: 104
[2021-12-21 16:15:39 +0100] [104] [INFO] Autorestarting worker after current request.
[2021-12-21 16:15:39 +0100] [104] [INFO] Worker exiting (pid: 104)
[2021-12-21 16:15:39 +0100] [105] [INFO] Booting worker with pid: 105
[2021-12-21 16:23:57 +0100] [105] [INFO] Autorestarting worker after current request.
[2021-12-21 16:23:57 +0100] [105] [INFO] Worker exiting (pid: 105)
[2021-12-21 16:23:57 +0100] [106] [INFO] Booting worker with pid: 106
[2021-12-21 16:32:15 +0100] [106] [INFO] Autorestarting worker after current request.
[2021-12-21 16:32:15 +0100] [106] [INFO] Worker exiting (pid: 106)
[2021-12-21 16:32:15 +0100] [107] [INFO] Booting worker with pid: 107
[2021-12-21 16:40:34 +0100] [107] [INFO] Autorestarting worker after current request.
[2021-12-21 16:40:34 +0100] [107] [INFO] Worker exiting (pid: 107)
[2021-12-21 16:40:34 +0100] [108] [INFO] Booting worker with pid: 108
[2021-12-21 16:48:52 +0100] [108] [INFO] Autorestarting worker after current request.
[2021-12-21 16:48:52 +0100] [108] [INFO] Worker exiting (pid: 108)
[2021-12-21 16:48:52 +0100] [109] [INFO] Booting worker with pid: 109
[2021-12-21 16:57:10 +0100] [109] [INFO] Autorestarting worker after current request.
[2021-12-21 16:57:10 +0100] [109] [INFO] Worker exiting (pid: 109)
[2021-12-21 16:57:10 +0100] [110] [INFO] Booting worker with pid: 110
[2021-12-21 17:05:28 +0100] [110] [INFO] Autorestarting worker after current request.
[2021-12-21 17:05:28 +0100] [110] [INFO] Worker exiting (pid: 110)
[2021-12-21 17:05:28 +0100] [111] [INFO] Booting worker with pid: 111
[2021-12-21 17:13:46 +0100] [111] [INFO] Autorestarting worker after current request.
[2021-12-21 17:13:46 +0100] [111] [INFO] Worker exiting (pid: 111)
[2021-12-21 17:13:46 +0100] [112] [INFO] Booting worker with pid: 112
[2021-12-21 17:22:05 +0100] [112] [INFO] Autorestarting worker after current request.
[2021-12-21 17:22:05 +0100] [112] [INFO] Worker exiting (pid: 112)
[2021-12-21 17:22:05 +0100] [113] [INFO] Booting worker with pid: 113
[2021-12-21 17:30:23 +0100] [113] [INFO] Autorestarting worker after current request.
[2021-12-21 17:30:23 +0100] [113] [INFO] Worker exiting (pid: 113)
[2021-12-21 17:30:23 +0100] [114] [INFO] Booting worker with pid: 114
[2021-12-21 17:38:41 +0100] [114] [INFO] Autorestarting worker after current request.
[2021-12-21 17:38:41 +0100] [114] [INFO] Worker exiting (pid: 114)
[2021-12-21 17:38:41 +0100] [115] [INFO] Booting worker with pid: 115
[2021-12-21 17:47:00 +0100] [115] [INFO] Autorestarting worker after current request.
[2021-12-21 17:47:00 +0100] [115] [INFO] Worker exiting (pid: 115)
[2021-12-21 17:47:00 +0100] [116] [INFO] Booting worker with pid: 116
[2021-12-21 17:55:18 +0100] [116] [INFO] Autorestarting worker after current request.
[2021-12-21 17:55:18 +0100] [116] [INFO] Worker exiting (pid: 116)
[2021-12-21 17:55:18 +0100] [117] [INFO] Booting worker with pid: 117
[2021-12-21 18:03:36 +0100] [117] [INFO] Autorestarting worker after current request.
[2021-12-21 18:03:36 +0100] [117] [INFO] Worker exiting (pid: 117)
[2021-12-21 18:03:36 +0100] [118] [INFO] Booting worker with pid: 118
[2021-12-21 18:11:55 +0100] [118] [INFO] Autorestarting worker after current request.
[2021-12-21 18:11:55 +0100] [118] [INFO] Worker exiting (pid: 118)
[2021-12-21 18:11:55 +0100] [119] [INFO] Booting worker with pid: 119
[2021-12-21 18:20:13 +0100] [119] [INFO] Autorestarting worker after current request.
[2021-12-21 18:20:13 +0100] [119] [INFO] Worker exiting (pid: 119)
[2021-12-21 18:20:13 +0100] [120] [INFO] Booting worker with pid: 120
[2021-12-21 18:28:31 +0100] [120] [INFO] Autorestarting worker after current request.
[2021-12-21 18:28:31 +0100] [120] [INFO] Worker exiting (pid: 120)
[2021-12-21 18:28:31 +0100] [121] [INFO] Booting worker with pid: 121
[2021-12-21 18:36:50 +0100] [121] [INFO] Autorestarting worker after current request.
[2021-12-21 18:36:50 +0100] [121] [INFO] Worker exiting (pid: 121)
[2021-12-21 18:36:50 +0100] [122] [INFO] Booting worker with pid: 122
[2021-12-21 18:45:08 +0100] [122] [INFO] Autorestarting worker after current request.
[2021-12-21 18:45:08 +0100] [122] [INFO] Worker exiting (pid: 122)
[2021-12-21 18:45:08 +0100] [123] [INFO] Booting worker with pid: 123
[2021-12-21 18:53:26 +0100] [123] [INFO] Autorestarting worker after current request.
[2021-12-21 18:53:26 +0100] [123] [INFO] Worker exiting (pid: 123)
[2021-12-21 18:53:26 +0100] [124] [INFO] Booting worker with pid: 124
[2021-12-21 19:01:45 +0100] [124] [INFO] Autorestarting worker after current request.
[2021-12-21 19:01:45 +0100] [124] [INFO] Worker exiting (pid: 124)
[2021-12-21 19:01:45 +0100] [125] [INFO] Booting worker with pid: 125
[2021-12-21 19:10:03 +0100] [125] [INFO] Autorestarting worker after current request.
[2021-12-21 19:10:03 +0100] [125] [INFO] Worker exiting (pid: 125)
[2021-12-21 19:10:03 +0100] [126] [INFO] Booting worker with pid: 126
[2021-12-21 19:18:21 +0100] [126] [INFO] Autorestarting worker after current request.
[2021-12-21 19:18:21 +0100] [126] [INFO] Worker exiting (pid: 126)
[2021-12-21 19:18:21 +0100] [127] [INFO] Booting worker with pid: 127
[2021-12-21 19:26:40 +0100] [127] [INFO] Autorestarting worker after current request.
[2021-12-21 19:26:40 +0100] [127] [INFO] Worker exiting (pid: 127)
[2021-12-21 19:26:40 +0100] [128] [INFO] Booting worker with pid: 128
[2021-12-21 19:34:58 +0100] [128] [INFO] Autorestarting worker after current request.
[2021-12-21 19:34:58 +0100] [128] [INFO] Worker exiting (pid: 128)
[2021-12-21 19:34:58 +0100] [129] [INFO] Booting worker with pid: 129
[2021-12-21 19:43:16 +0100] [129] [INFO] Autorestarting worker after current request.
[2021-12-21 19:43:16 +0100] [129] [INFO] Worker exiting (pid: 129)
[2021-12-21 19:43:16 +0100] [130] [INFO] Booting worker with pid: 130
[2021-12-21 19:51:34 +0100] [130] [INFO] Autorestarting worker after current request.
[2021-12-21 19:51:34 +0100] [130] [INFO] Worker exiting (pid: 130)
[2021-12-21 19:51:34 +0100] [131] [INFO] Booting worker with pid: 131
[2021-12-21 19:59:52 +0100] [131] [INFO] Autorestarting worker after current request.
[2021-12-21 19:59:52 +0100] [131] [INFO] Worker exiting (pid: 131)
[2021-12-21 19:59:52 +0100] [132] [INFO] Booting worker with pid: 132
[2021-12-21 20:08:11 +0100] [132] [INFO] Autorestarting worker after current request.
[2021-12-21 20:08:11 +0100] [132] [INFO] Worker exiting (pid: 132)
[2021-12-21 20:08:11 +0100] [133] [INFO] Booting worker with pid: 133
[2021-12-21 20:16:29 +0100] [133] [INFO] Autorestarting worker after current request.
[2021-12-21 20:16:29 +0100] [133] [INFO] Worker exiting (pid: 133)
[2021-12-21 20:16:29 +0100] [134] [INFO] Booting worker with pid: 134
[2021-12-21 20:24:47 +0100] [134] [INFO] Autorestarting worker after current request.
[2021-12-21 20:24:47 +0100] [134] [INFO] Worker exiting (pid: 134)
[2021-12-21 20:24:47 +0100] [135] [INFO] Booting worker with pid: 135
[2021-12-21 20:33:06 +0100] [135] [INFO] Autorestarting worker after current request.
[2021-12-21 20:33:06 +0100] [135] [INFO] Worker exiting (pid: 135)
[2021-12-21 20:33:06 +0100] [136] [INFO] Booting worker with pid: 136
[2021-12-21 20:41:24 +0100] [136] [INFO] Autorestarting worker after current request.
[2021-12-21 20:41:24 +0100] [136] [INFO] Worker exiting (pid: 136)
[2021-12-21 20:41:24 +0100] [137] [INFO] Booting worker with pid: 137
[2021-12-21 20:49:42 +0100] [137] [INFO] Autorestarting worker after current request.
[2021-12-21 20:49:42 +0100] [137] [INFO] Worker exiting (pid: 137)
[2021-12-21 20:49:42 +0100] [138] [INFO] Booting worker with pid: 138
[2021-12-21 20:58:01 +0100] [138] [INFO] Autorestarting worker after current request.
[2021-12-21 20:58:01 +0100] [138] [INFO] Worker exiting (pid: 138)
[2021-12-21 20:58:01 +0100] [139] [INFO] Booting worker with pid: 139
[2021-12-21 21:06:19 +0100] [139] [INFO] Autorestarting worker after current request.
[2021-12-21 21:06:19 +0100] [139] [INFO] Worker exiting (pid: 139)
[2021-12-21 21:06:19 +0100] [140] [INFO] Booting worker with pid: 140
[2021-12-21 21:14:37 +0100] [140] [INFO] Autorestarting worker after current request.
[2021-12-21 21:14:37 +0100] [140] [INFO] Worker exiting (pid: 140)
[2021-12-21 21:14:37 +0100] [141] [INFO] Booting worker with pid: 141
[2021-12-21 21:22:56 +0100] [141] [INFO] Autorestarting worker after current request.
[2021-12-21 21:22:56 +0100] [141] [INFO] Worker exiting (pid: 141)
[2021-12-21 21:22:56 +0100] [142] [INFO] Booting worker with pid: 142
[2021-12-21 21:31:14 +0100] [142] [INFO] Autorestarting worker after current request.
[2021-12-21 21:31:14 +0100] [142] [INFO] Worker exiting (pid: 142)
[2021-12-21 21:31:14 +0100] [143] [INFO] Booting worker with pid: 143
[2021-12-21 21:39:32 +0100] [143] [INFO] Autorestarting worker after current request.
[2021-12-21 21:39:32 +0100] [143] [INFO] Worker exiting (pid: 143)
[2021-12-21 21:39:32 +0100] [144] [INFO] Booting worker with pid: 144
[2021-12-21 21:47:51 +0100] [144] [INFO] Autorestarting worker after current request.
[2021-12-21 21:47:51 +0100] [144] [INFO] Worker exiting (pid: 144)
[2021-12-21 21:47:51 +0100] [145] [INFO] Booting worker with pid: 145
[2021-12-21 21:56:09 +0100] [145] [INFO] Autorestarting worker after current request.
[2021-12-21 21:56:09 +0100] [145] [INFO] Worker exiting (pid: 145)
[2021-12-21 21:56:09 +0100] [146] [INFO] Booting worker with pid: 146
[2021-12-21 22:04:22 +0100] [146] [INFO] Autorestarting worker after current request.
[2021-12-21 22:04:22 +0100] [146] [INFO] Worker exiting (pid: 146)
[2021-12-21 22:04:22 +0100] [147] [INFO] Booting worker with pid: 147
[2021-12-21 22:12:41 +0100] [147] [INFO] Autorestarting worker after current request.
[2021-12-21 22:12:41 +0100] [147] [INFO] Worker exiting (pid: 147)
[2021-12-21 22:12:41 +0100] [148] [INFO] Booting worker with pid: 148
[2021-12-21 22:20:59 +0100] [148] [INFO] Autorestarting worker after current request.
[2021-12-21 22:20:59 +0100] [148] [INFO] Worker exiting (pid: 148)
[2021-12-21 22:20:59 +0100] [149] [INFO] Booting worker with pid: 149
[2021-12-21 22:29:17 +0100] [149] [INFO] Autorestarting worker after current request.
[2021-12-21 22:29:17 +0100] [149] [INFO] Worker exiting (pid: 149)
[2021-12-21 22:29:17 +0100] [150] [INFO] Booting worker with pid: 150
[2021-12-21 22:37:36 +0100] [150] [INFO] Autorestarting worker after current request.
[2021-12-21 22:37:36 +0100] [150] [INFO] Worker exiting (pid: 150)
[2021-12-21 22:37:36 +0100] [151] [INFO] Booting worker with pid: 151
[2021-12-21 22:45:54 +0100] [151] [INFO] Autorestarting worker after current request.
[2021-12-21 22:45:54 +0100] [151] [INFO] Worker exiting (pid: 151)
[2021-12-21 22:45:54 +0100] [152] [INFO] Booting worker with pid: 152
[2021-12-21 22:54:12 +0100] [152] [INFO] Autorestarting worker after current request.
[2021-12-21 22:54:12 +0100] [152] [INFO] Worker exiting (pid: 152)
[2021-12-21 22:54:12 +0100] [153] [INFO] Booting worker with pid: 153
[2021-12-21 23:02:31 +0100] [153] [INFO] Autorestarting worker after current request.
[2021-12-21 23:02:31 +0100] [153] [INFO] Worker exiting (pid: 153)
[2021-12-21 23:02:31 +0100] [154] [INFO] Booting worker with pid: 154
[2021-12-21 23:10:49 +0100] [154] [INFO] Autorestarting worker after current request.
[2021-12-21 23:10:49 +0100] [154] [INFO] Worker exiting (pid: 154)
[2021-12-21 23:10:49 +0100] [155] [INFO] Booting worker with pid: 155
[2021-12-21 23:19:07 +0100] [155] [INFO] Autorestarting worker after current request.
[2021-12-21 23:19:07 +0100] [155] [INFO] Worker exiting (pid: 155)
[2021-12-21 23:19:07 +0100] [156] [INFO] Booting worker with pid: 156
[2021-12-21 23:27:26 +0100] [156] [INFO] Autorestarting worker after current request.
[2021-12-21 23:27:26 +0100] [156] [INFO] Worker exiting (pid: 156)
[2021-12-21 23:27:26 +0100] [157] [INFO] Booting worker with pid: 157
[2021-12-21 23:35:44 +0100] [157] [INFO] Autorestarting worker after current request.
[2021-12-21 23:35:44 +0100] [157] [INFO] Worker exiting (pid: 157)
[2021-12-21 23:35:44 +0100] [158] [INFO] Booting worker with pid: 158
[2021-12-21 23:44:03 +0100] [158] [INFO] Autorestarting worker after current request.
[2021-12-21 23:44:03 +0100] [158] [INFO] Worker exiting (pid: 158)
[2021-12-21 23:44:03 +0100] [159] [INFO] Booting worker with pid: 159
[2021-12-21 23:52:21 +0100] [159] [INFO] Autorestarting worker after current request.
[2021-12-21 23:52:21 +0100] [159] [INFO] Worker exiting (pid: 159)
[2021-12-21 23:52:21 +0100] [160] [INFO] Booting worker with pid: 160
[2021-12-22 00:00:39 +0100] [160] [INFO] Autorestarting worker after current request.
[2021-12-22 00:00:39 +0100] [160] [INFO] Worker exiting (pid: 160)
[2021-12-22 00:00:39 +0100] [161] [INFO] Booting worker with pid: 161
[2021-12-22 00:08:58 +0100] [161] [INFO] Autorestarting worker after current request.
[2021-12-22 00:08:58 +0100] [161] [INFO] Worker exiting (pid: 161)
[2021-12-22 00:08:58 +0100] [162] [INFO] Booting worker with pid: 162
[2021-12-22 00:17:16 +0100] [162] [INFO] Autorestarting worker after current request.
[2021-12-22 00:17:16 +0100] [162] [INFO] Worker exiting (pid: 162)
[2021-12-22 00:17:16 +0100] [163] [INFO] Booting worker with pid: 163
[2021-12-22 00:25:34 +0100] [163] [INFO] Autorestarting worker after current request.
[2021-12-22 00:25:34 +0100] [163] [INFO] Worker exiting (pid: 163)
[2021-12-22 00:25:34 +0100] [164] [INFO] Booting worker with pid: 164
[2021-12-22 00:33:53 +0100] [164] [INFO] Autorestarting worker after current request.
[2021-12-22 00:33:53 +0100] [164] [INFO] Worker exiting (pid: 164)
[2021-12-22 00:33:53 +0100] [165] [INFO] Booting worker with pid: 165
[2021-12-22 00:42:11 +0100] [165] [INFO] Autorestarting worker after current request.
[2021-12-22 00:42:11 +0100] [165] [INFO] Worker exiting (pid: 165)
[2021-12-22 00:42:11 +0100] [166] [INFO] Booting worker with pid: 166
[2021-12-22 00:50:29 +0100] [166] [INFO] Autorestarting worker after current request.
[2021-12-22 00:50:29 +0100] [166] [INFO] Worker exiting (pid: 166)
[2021-12-22 00:50:29 +0100] [167] [INFO] Booting worker with pid: 167
[2021-12-22 00:58:48 +0100] [167] [INFO] Autorestarting worker after current request.
[2021-12-22 00:58:48 +0100] [167] [INFO] Worker exiting (pid: 167)
[2021-12-22 00:58:48 +0100] [168] [INFO] Booting worker with pid: 168
[2021-12-22 01:07:06 +0100] [168] [INFO] Autorestarting worker after current request.
[2021-12-22 01:07:06 +0100] [168] [INFO] Worker exiting (pid: 168)
[2021-12-22 01:07:06 +0100] [169] [INFO] Booting worker with pid: 169
[2021-12-22 01:15:24 +0100] [169] [INFO] Autorestarting worker after current request.
[2021-12-22 01:15:24 +0100] [169] [INFO] Worker exiting (pid: 169)
[2021-12-22 01:15:24 +0100] [170] [INFO] Booting worker with pid: 170
[2021-12-22 01:23:43 +0100] [170] [INFO] Autorestarting worker after current request.
[2021-12-22 01:23:43 +0100] [170] [INFO] Worker exiting (pid: 170)
[2021-12-22 01:23:43 +0100] [171] [INFO] Booting worker with pid: 171
[2021-12-22 01:32:01 +0100] [171] [INFO] Autorestarting worker after current request.
[2021-12-22 01:32:01 +0100] [171] [INFO] Worker exiting (pid: 171)
[2021-12-22 01:32:01 +0100] [172] [INFO] Booting worker with pid: 172
[2021-12-22 01:40:19 +0100] [172] [INFO] Autorestarting worker after current request.
[2021-12-22 01:40:19 +0100] [172] [INFO] Worker exiting (pid: 172)
[2021-12-22 01:40:19 +0100] [173] [INFO] Booting worker with pid: 173
[2021-12-22 01:48:38 +0100] [173] [INFO] Autorestarting worker after current request.
[2021-12-22 01:48:38 +0100] [173] [INFO] Worker exiting (pid: 173)
[2021-12-22 01:48:38 +0100] [174] [INFO] Booting worker with pid: 174
[2021-12-22 01:56:56 +0100] [174] [INFO] Autorestarting worker after current request.
[2021-12-22 01:56:56 +0100] [174] [INFO] Worker exiting (pid: 174)
[2021-12-22 01:56:56 +0100] [175] [INFO] Booting worker with pid: 175
[2021-12-22 02:05:14 +0100] [175] [INFO] Autorestarting worker after current request.
[2021-12-22 02:05:14 +0100] [175] [INFO] Worker exiting (pid: 175)
[2021-12-22 02:05:14 +0100] [176] [INFO] Booting worker with pid: 176
[2021-12-22 02:13:33 +0100] [176] [INFO] Autorestarting worker after current request.
[2021-12-22 02:13:33 +0100] [176] [INFO] Worker exiting (pid: 176)
[2021-12-22 02:13:33 +0100] [177] [INFO] Booting worker with pid: 177
[2021-12-22 02:21:51 +0100] [177] [INFO] Autorestarting worker after current request.
[2021-12-22 02:21:51 +0100] [177] [INFO] Worker exiting (pid: 177)
[2021-12-22 02:21:51 +0100] [178] [INFO] Booting worker with pid: 178
[2021-12-22 02:30:09 +0100] [178] [INFO] Autorestarting worker after current request.
[2021-12-22 02:30:09 +0100] [178] [INFO] Worker exiting (pid: 178)
[2021-12-22 02:30:09 +0100] [179] [INFO] Booting worker with pid: 179
[2021-12-22 02:38:28 +0100] [179] [INFO] Autorestarting worker after current request.
[2021-12-22 02:38:28 +0100] [179] [INFO] Worker exiting (pid: 179)
[2021-12-22 02:38:28 +0100] [180] [INFO] Booting worker with pid: 180
[2021-12-22 02:46:46 +0100] [180] [INFO] Autorestarting worker after current request.
[2021-12-22 02:46:46 +0100] [180] [INFO] Worker exiting (pid: 180)
[2021-12-22 02:46:46 +0100] [181] [INFO] Booting worker with pid: 181
[2021-12-22 02:55:04 +0100] [181] [INFO] Autorestarting worker after current request.
[2021-12-22 02:55:04 +0100] [181] [INFO] Worker exiting (pid: 181)
[2021-12-22 02:55:04 +0100] [182] [INFO] Booting worker with pid: 182
[2021-12-22 03:03:23 +0100] [182] [INFO] Autorestarting worker after current request.
[2021-12-22 03:03:23 +0100] [182] [INFO] Worker exiting (pid: 182)
[2021-12-22 03:03:23 +0100] [183] [INFO] Booting worker with pid: 183
2021-12-22 03:04:56,401 ERROR mixins run_once 103 | dsmr_backend.management.commands.dsmr_backend: [!] Exception raised. Traceback (most recent call last):

File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/dsmr/dsmr_backend/mixins.py", line 92, in run_once
self.run(data=self.data, **options)
File "/dsmr/dsmr_backend/management/commands/dsmr_backend.py", line 33, in run
dsmr_backend.services.schedule.execute_scheduled_processes()
File "/dsmr/dsmr_backend/services/schedule.py", line 29, in execute_scheduled_processes
logger.debug('SP: %s backend service(s) ready to run', len(calls))
File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 269, in __len__
self._fetch_all()
File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1308, in _fetch_all
self._result_cache = list(self._iterable_class(self))
File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 53, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
cursor.execute(sql, params)
File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
with self.db.wrap_database_errors:
File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
django.db.utils.OperationalError: terminating connection due to administrator command
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.


2021-12-22 03:04:57,492 INFO exited: dsmr_backend (exit status 0; expected)
2021-12-22 03:04:59,494 WARN received SIGQUIT indicating exit request
2021-12-22 03:04:59,495 INFO waiting for processes, dsmr_webinterface, nginx to die
2021-12-22 03:04:59,522 INFO stopped: nginx (exit status 0)
[2021-12-22 03:04:59 +0100] [183] [INFO] Worker exiting (pid: 183)
[2021-12-22 03:04:59 +0100] [20] [INFO] Handling signal: term
[2021-12-22 03:04:59 +0100] [20] [INFO] Shutting down: Master
2021-12-22 03:04:59,645 INFO stopped: dsmr_webinterface (exit status 0)
2021-12-22 03:05:02,649 INFO waiting for processes to die
2021-12-22 03:05:02,649 INFO stopped: processes (terminated by SIGTERM)```

### DSMR-reader version

4.19

### DSMR-reader platform

Docker (e.g. Xirixiz)

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                      v4.19 / v3.10.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             418524
    Consumption records electricity / gas (est.)                                                31594 / 26594

UNRESOLVED ISSUES
    Geen recente metingen ontvangen                                                             4 uur geleden
```

**Comment by dennissiemensma** [comment]
Het kan komen door #1541. Het lijkt erop dat de DB afsluit: "terminating connection due to administrator commandserver closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request."

**Comment by Diondk** [comment]
Ik had dit ook al voor dat ik mijn database heb geupgrade naar versie 14, maar zal mijn backup vanavond is uitzetten op mijn containers misschien dat hij het morgen nog doet dan.

**Comment by dennissiemensma** [comment]
Je kunt dit dan het beste bij xirixiz voorleggen. Ik weet namelijk niet of het dsm gerelateerd of doxker gerelateerd is eerlijk gezegd.

**Comment by Diondk** [comment]
Na het uitzetten van de backup voor de database container crasht hij inderdaad niet meer, raar dat het hiervoor nooit gebeurde. Zal na de kerst een issue maken bij xirixiz.

**Comment by dennissiemensma** [comment]
Dank voor je snelle update! 

De oorzaak is de Postgres-versie-mismatch, maar het gevolg (dat alles stopt) is wellicht een bijeffect van hoe processen nu intern draaien in de Docker-versie. https://github.com/xirixiz/dsmr-reader-docker/issues/241#issuecomment-999032323
