### ISSUE TITLE
🙋 Spontaan geen data meer - Permission denied: '/dev/ttyUSB0

### ISSUE THREAD

**Issue by Jagermyster** [dsmrreader/dsmr-reader#1547]
### Description

Sinds afgelopen nacht lijkt DSMR geen verbinding meer te hebben met ttyUSB0 waar de P1 kabel op zit.
Reboot van home-assistant heeft niet geholpen en uit de logs wordt ik ook niet veel wijzer behalve dat er een error is, en dan met name iets met permissions. Dat is vreemd want alles heeft altijd prima gewerkt en er is tussen het moment van werken en niet meer werken ook niets veranderd. Geen updates of reboots oid.
Iemand bekend met deze error?

### DSMR-reader version

4.19

### DSMR-reader platform

Other

### Debug info dump

```shell
Starting DSMR Reader - datalogger...
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
2022-01-04 19:17:27,956 ERROR    mixins       run_once                        103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 34, in read_telegram
    serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
  File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/dsmr_backend/mixins.py", line 92, in run_once
    self.run(data=self.data, **options)
  File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
    telegram = next(self.telegram_generator)
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 36, in read_telegram
    raise RuntimeError('Failed to connect: {}', error)
RuntimeError: ('Failed to connect: {}', SerialException(13, "could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'"))

----

DSMR-READER
    App / Python / Database                                                      v4.19 / v3.10.0 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 672h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             424489
    Consumption records electricity / gas (est.)                                                46109 / 14279

UNRESOLVED ISSUES
    No recent readings received                                                                  17 hours ago
```
Edit: Never mind. Error was in the Home assistant version.
https://github.com/sanderdw/hassio-addons/issues/26

**Comment by dennissiemensma** [comment]
Bedankt voor je melding en update!

Een volgende keer zou je nog kunnen proberen om eerst handmatig de poort uit te lezen. Als dat niet lukt, dan is de kans groot dat het aan de kabel of softwareverbinding zelf zit:

```
sudo su - dsmr
cu -l /dev/ttyUSB0 -s 115200 --parity=none -E q
```
