### ISSUE TITLE
🚨 Sinds ik verhuisd ben moet ik na een reboot van unraid dsmr reader container opnieuw deployen

### ISSUE THREAD

**Issue by Diondk** [dsmrreader/dsmr-reader#1625]
### Description

Sinds ik verhuisd ben krijg ik na elke reboot van mijn unraid bak een gateway 500 error na het verwijderen van de container en deze opnieuw deployen werkt alles weer. 

Mijn configuratie staat ingesteld op receiver aangezien er in de meterkast een raspberry hangt met de verstuurder. 

Ik zie alleen deze error in de logs files van de container:

`File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 37, in read_telegram
serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
instance.open()
File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 316, in open
raise SerialException("Port must be configured before it can be used.")
serial.serialutil.SerialException: Port must be configured before it can be used.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/dsmr_backend/mixins.py", line 92, in run_once
self.run(data=self.data, **options)
File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
telegram = next(self.telegram_generator)
File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 39, in read_telegram
raise RuntimeError('Failed to connect: {}', error)

RuntimeError: ('Failed to connect: {}', SerialException('Port must be configured before it can be used.'))`

### DSMR-reader version

DSMR-reader v5.1

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                       v5.1 / v3.10.4 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 5.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                             633553
    Consumption records electricity / gas (est.)                                                40135 / 32570
```

**Comment by Diondk** [comment]
Deze kan dicht wou hem bij xiriz openen..
