### ISSUE TITLE
🚨 DSMR container blijft datalogger starten wanneer hij ingesteld staat op standalone

### ISSUE THREAD

**Issue by Diondk** [dsmrreader/dsmr-reader#1642]
### Description

Ik heb een losse datalogger in de meterkast, mijn dsmr staat ingesteld als receiver maar toch zie ik constant in de log files dat de datalogger gestart wordt.

`Reader - datalogger...
Current logging level set to "ERROR". More information can be found here: https://dsmr-reader.readthedocs.io/en/latest/how-to/troubleshooting/enabling-debug-logging.html
2022-06-09 11:24:46,793 ERROR    mixins       run_once                        103 | dsmr_datalogger.management.commands.dsmr_datalogger: [!] Exception raised. Traceback (most recent call last):
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 37, in read_telegram
    serial_handle = serial.serial_for_url(url=url_or_port, timeout=MAX_READ_TIMEOUT, **serial_kwargs)
  File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 316, in open
    raise SerialException("Port must be configured before it can be used.")
serial.serialutil.SerialException: Port must be configured before it can be used.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/dsmr_backend/mixins.py", line 92, in run_once
    self.run(data=self.data, **options)
  File "/app/dsmr_datalogger/management/commands/dsmr_datalogger.py", line 29, in run
    telegram = next(self.telegram_generator)
  File "/app/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py", line 39, in read_telegram
    raise RuntimeError('Failed to connect: {}', error)
RuntimeError: ('Failed to connect: {}', SerialException('Port must be configured before it can be used.'))
`

### DSMR-reader version

5.2

### Debug info dump

```shell
DSMR-READER
    App / Python / Database                                                       v5.2 / v3.10.4 / postgresql
    BE sleep / DL sleep / Retention / Override                                     1.0s / 1.0s / 168h / False
    Latest telegram version read / Parser settings                                                 "50" / "4"

DATA
    Telegrams total (est.)                                                                              48880
    Consumption records electricity / gas (est.)                                                40524 / 34636
```

**Comment by Diondk** [comment]
Uh laat maar, had nog een oude variabel staan.
vervangen voor deze DSMRREADER_REMOTE_DATALOGGER_MODE en nu is de melding.

**Comment by dennissiemensma** [comment]
~Bedankt voor je melding. Ik zal nog een extra notitie bovenaan het script zetten dat de envvars ooit hernoemd zijn~

Nevermind, er staat al een soort van iets.
